[[pages]]
path = "about.py"
name = "Ğ Ğ½Ğ°Ñ"
icon = "ğŸ“"

[[pages]]
name = "Ğ¡Ñ‚Ğ¸Ñ…Ğ¸Ğ¹Ğ½Ñ‹Ğ¹ Ğ¿Ğ¾Ñ€ÑĞ´Ğ¾Ğº"
icon = "ğŸ”®"
is_section = true

[[pages]]
path = "StihiyniyPoryadok/main.py"
name = "Ğ“Ğ»Ğ°Ğ²Ğ½Ğ¾Ğµ"
icon = "ğŸ“•"